server:
  port: 8761
eureka:
  datacenter: cloud
  server: 
     enable-self-preservation: false
  client: 
    #是否向服务注册中心注册自己
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka     
  instance: 
      #服务注册中心实例的主机名
      hostname: localhost

 # 刷新时，关闭安全验证
management: 
   security: 
      enabled: false

spring: 
  rabbitmq:
     host: 192.163.20.86
     port: 5672
     username: bh
     password: bh